import sys, os, time
W = r"C:/Users/admin/WorkBuddy/2026-09-29-10-57-50"
sys.path.insert(0, os.path.join(W, ".tools"))
from abx import run

def ev(js, t=45):
    return run(["eval", "--stdin"], js, t).strip()

def shot(name):
    run(["screenshot", os.path.join(W, ".ui-shots", name)], None, 60)

def layout():
    return ev("JSON.stringify({hScroll: document.documentElement.scrollWidth > innerWidth + 1, minBtn: Math.min(...[...document.querySelectorAll('button')].map(b=>Math.round(b.getBoundingClientRect().height)))})")

run(["set", "viewport", "390", "844"], None, 40)

print("=" * 30)
print("1. 首页理念区新文案 + 无demoEntry")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/index.html?t=n1"], None, 45)
time.sleep(1.4)
print("理念:", ev("""(() => {
  const c = document.querySelector('.idea-card');
  return JSON.stringify({
    title: c.querySelector('.idea-title').textContent,
    sub: c.querySelector('.idea-sub').textContent.replace(/\\s+/g,' ').trim(),
    before: c.querySelector('.idea-row:not(.is-now) .idea-name').textContent,
    beforeList: [...c.querySelectorAll('.idea-row:not(.is-now) .idea-list li')].map(x=>x.textContent),
    nowList: [...c.querySelectorAll('.idea-row.is-now .idea-list li')].map(x=>x.textContent),
    foot: c.querySelector('.idea-foot').textContent.replace(/\\s+/g,' ').trim()
  });
})()"""))
print("入口数(应=3,无demo):", ev("document.querySelectorAll('.choice.entry').length"), "demoEntry存在:", ev("!!document.getElementById('demoEntry')"))
print("布局:", layout())
ev("document.querySelector('.idea-card').scrollIntoView({block:'start'}); 'ok'")
time.sleep(0.4)
shot("p4n-1-idea.png")

print()
print("=" * 30)
print("2. 发现页案例：只填入不自动跑")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/index.html?t=n2"], None, 45)
time.sleep(0.8)
ev("sessionStorage.clear(); 'ok'")
ev("document.querySelector('.choice.entry[data-target=family]').click(); 'ok'")
time.sleep(1.0)
ev("document.querySelector('#operatorGrid .choice[data-role=\"女儿\"]').click(); 'ok'")
ev("document.querySelector('#beneficiaryGrid .choice[data-role=\"父亲\"]').click(); 'ok'")
ev("document.getElementById('nextBtn').click(); 'ok'")
time.sleep(1.2)
print("案例按钮文案:", ev("document.getElementById('caseBtn').textContent"))
print("案例标签:", ev("document.querySelector('.case-badge').textContent"))
ev("document.getElementById('caseBtn').click(); 'ok'")
time.sleep(0.6)
print("填入后input:", ev("document.getElementById('situation').value"))
print("点击后卡片数(应=0,未自动跑):", ev("document.querySelectorAll('.result-card').length"))
print("聚焦元素:", ev("document.activeElement.id"))
ev("document.getElementById('caseBtn').scrollIntoView({block:'center'}); 'ok'")
time.sleep(0.4)
shot("p4n-2-case.png")

print()
print("=" * 30)
print("3. 手动点开始发现 → 场景区新文案")
print("=" * 30)
ev("document.getElementById('discoverBtn').click(); 'ok'")
time.sleep(3.2)
print("卡片数:", ev("document.querySelectorAll('.result-card').length"))
print("场景lead:", ev("(document.querySelector('.scene-lead')||{}).textContent"))
print("场景角标:", ev("JSON.stringify([...document.querySelectorAll('.scene-row')].map(r=>r.querySelector('.scene-badge').textContent))"))
print("布局:", layout())
ev("document.querySelector('.scene-box').scrollIntoView({block:'center'}); 'ok'")
time.sleep(0.4)
shot("p4n-3-scenes.png")

print()
print("=" * 30)
print("4. 空状态·状态1(外地)")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/index.html?t=n3"], None, 45)
time.sleep(0.8)
ev("sessionStorage.clear(); 'ok'")
ev("document.querySelector('.choice.entry[data-target=family]').click(); 'ok'")
time.sleep(1.0)
ev("document.querySelector('#operatorGrid .choice[data-role=\"女儿\"]').click(); 'ok'")
ev("document.querySelector('#beneficiaryGrid .choice[data-role=\"父亲\"]').click(); 'ok'")
ev("document.getElementById('nextBtn').click(); 'ok'")
time.sleep(1.2)
ev("document.getElementById('situation').value='我父亲在佛山住，最近身体还行'; 'ok'")
ev("document.getElementById('discoverBtn').click(); 'ok'")
time.sleep(3.0)
print("空态标题:", ev("(document.querySelector('.empty-title')||{}).textContent"))
print("空态sub:", ev("(document.querySelector('.empty-sub')||{}).textContent.replace(/\\s+/g,' ').trim()"))
print("可能原因:", ev("JSON.stringify([...document.querySelectorAll('.empty-block')[0].querySelectorAll('li')].map(x=>x.textContent))"))
print("含「没有资格/不符合」:", ev("/没有资格|不符合/.test(document.querySelector('.empty-card').textContent)"))
ev("document.querySelector('.empty-card').scrollIntoView({block:'start'}); 'ok'")
time.sleep(0.4)
shot("p4n-4-empty1.png")

print()
print("=" * 30)
print("5. 空状态·状态2(信息不足)")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/index.html?t=n4"], None, 45)
time.sleep(0.8)
ev("sessionStorage.clear(); 'ok'")
ev("document.querySelector('.choice.entry[data-target=family]').click(); 'ok'")
time.sleep(1.0)
ev("document.querySelector('#operatorGrid .choice[data-role=\"女儿\"]').click(); 'ok'")
ev("document.querySelector('#beneficiaryGrid .choice[data-role=\"父亲\"]').click(); 'ok'")
ev("document.getElementById('nextBtn').click(); 'ok'")
time.sleep(1.2)
ev("document.getElementById('situation').value='我父亲在广州'; 'ok'")
ev("document.getElementById('discoverBtn').click(); 'ok'")
time.sleep(3.0)
print("空态标题:", ev("(document.querySelector('.empty-title')||{}).textContent"))
print("可能原因:", ev("JSON.stringify([...document.querySelectorAll('.empty-block')[0].querySelectorAll('li')].map(x=>x.textContent))"))

print()
print("=" * 30)
print("6. 本人模式案例只填入 + 无「老人」")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/self.html?t=n5"], None, 45)
time.sleep(1.0)
ev("sessionStorage.clear(); 'ok'")
run(["open", "http://127.0.0.1:8000/self.html?t=n5b"], None, 45)
time.sleep(1.2)
ev("document.getElementById('caseBtn').click(); 'ok'")
time.sleep(0.5)
print("填入:", ev("document.getElementById('situation').value"))
print("点击后卡片数(应=0):", ev("document.querySelectorAll('.result-card').length"))
ev("document.getElementById('discoverBtn').click(); 'ok'")
time.sleep(3.2)
print("本人模式卡片数:", ev("document.querySelectorAll('.result-card').length"))
print("结果区「老人」次数:", ev("(() => { const a=document.getElementById('resultArea'); return (a.textContent.match(/老人/g)||[]).length; })()"))
print("布局:", layout())

print()
print("=" * 30)
print("7. 详情页五问回归")
print("=" * 30)
ev("document.querySelector('.result-card').click(); 'ok'")
time.sleep(2.4)
print("五问:", ev("JSON.stringify([...document.querySelectorAll('.q-title')].map(x=>x.textContent))"))
print("信任卡行数:", ev("document.querySelectorAll('.tc-row').length"))
