import sys, os, time
W = r"C:/Users/admin/WorkBuddy/2026-09-29-10-57-50"
sys.path.insert(0, os.path.join(W, ".tools"))
from abx import run

def ev(js, t=45):
    return run(["eval", "--stdin"], js, t).strip()

def shot(name):
    run(["screenshot", os.path.join(W, ".ui-shots", name)], None, 60)

def layout():
    return ev("JSON.stringify({hScroll: document.documentElement.scrollWidth > innerWidth + 1, minBtn: Math.min(...[...document.querySelectorAll('button')].map(b=>Math.round(b.getBoundingClientRect().height)))})")

run(["set", "viewport", "390", "844"], None, 40)

print("=" * 30)
print("1. 首页演示入口")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/index.html?t=p5a"], None, 45)
time.sleep(1.4)
ev("sessionStorage.clear(); 'ok'")
run(["open", "http://127.0.0.1:8000/index.html?t=p5a2"], None, 45)
time.sleep(1.4)
print("演示按钮:", ev("document.getElementById('demoEntry').textContent.replace(/\\s+/g,' ').trim()"))
print("布局:", layout())
ev("document.getElementById('demoEntry').scrollIntoView({block:'center'}); 'ok'")
time.sleep(0.4)
shot("p5-1-demo-entry.png")

print()
print("=" * 30)
print("2. 点击演示 → 家庭页（banner + 回填）")
print("=" * 30)
ev("document.getElementById('demoEntry').click(); 'ok'")
time.sleep(1.4)
print("落地:", ev("location.pathname"))
print("banner:", ev("(() => { const b=document.querySelector('.demo-banner'); return b ? b.textContent.replace(/\\s+/g,' ').trim() : 'NO BANNER'; })()"))
print("operator已选:", ev("document.querySelector('#operatorGrid .choice.selected')?.dataset.role"))
print("beneficiary已选:", ev("document.querySelector('#beneficiaryGrid .choice.selected')?.dataset.role"))
print("confirmCheck:", ev("document.getElementById('confirmCheck').checked"))
print("nextBtn disabled:", ev("document.getElementById('nextBtn').disabled"))
print("布局:", layout())
ev("document.querySelector('.steps-bar').scrollIntoView({block:'start'}); 'ok'")
time.sleep(0.4)
shot("p5-2-family.png")

print()
print("=" * 30)
print("3. 下一步 → 发现页（banner + 自动填入 + 不自动跑）")
print("=" * 30)
ev("document.getElementById('nextBtn').click(); 'ok'")
time.sleep(1.4)
print("落地:", ev("location.pathname"))
print("banner:", ev("!!document.querySelector('.demo-banner')"))
print("input已填入:", ev("document.getElementById('situation').value"))
print("卡片数(应=0,未自动跑):", ev("document.querySelectorAll('.result-card').length"))
print("布局:", layout())
ev("document.getElementById('situation').scrollIntoView({block:'center'}); 'ok'")
time.sleep(0.4)
shot("p5-3-discover-prefill.png")

print()
print("=" * 30)
print("4. 手动开始发现 → AI流程 → 场景 → 结果")
print("=" * 30)
ev("document.getElementById('discoverBtn').click(); 'ok'")
time.sleep(3.4)
print("卡片数:", ev("document.querySelectorAll('.result-card').length"))
print("场景区:", ev("(document.querySelector('.scene-lead')||{}).textContent"))
print("banner仍存在:", ev("!!document.querySelector('.demo-banner')"))
print("布局:", layout())
ev("document.querySelector('.scene-box').scrollIntoView({block:'center'}); 'ok'")
time.sleep(0.4)
shot("p5-4-results.png")

print()
print("=" * 30)
print("5. 点结果卡 → 详情页（banner + 五问）")
print("=" * 30)
ev("document.querySelector('.result-card').click(); 'ok'")
time.sleep(2.4)
print("落地:", ev("location.pathname + location.search"))
print("banner:", ev("!!document.querySelector('.demo-banner')"))
print("五问:", ev("JSON.stringify([...document.querySelectorAll('.q-title')].map(x=>x.textContent))"))
print("信任卡:", ev("document.querySelectorAll('.tc-row').length"))
print("布局:", layout())
ev("document.querySelector('.trust-card').scrollIntoView({block:'center'}); 'ok'")
time.sleep(0.4)
shot("p5-5-detail.png")

print()
print("=" * 30)
print("6. 返回发现页 → 应自动跑（demo已清除）")
print("=" * 30)
ev("history.back(); 'ok'")
time.sleep(3.4)
print("落地:", ev("location.pathname"))
print("卡片数(应>0,自动跑):", ev("document.querySelectorAll('.result-card').length"))
print("banner仍存在:", ev("!!document.querySelector('.demo-banner')"))

print()
print("=" * 30)
print("7. 正常入口 → demoBanner 清除")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/index.html?t=p5b"], None, 45)
time.sleep(1.0)
ev("sessionStorage.setItem('policy_finder_session', JSON.stringify({demoBanner:true, demo:false})); 'ok'")
run(["open", "http://127.0.0.1:8000/index.html?t=p5b2"], None, 45)
time.sleep(1.0)
ev("document.querySelector('.choice.entry[data-target=parents]').click(); 'ok'")
time.sleep(1.2)
print("正常入口落地:", ev("location.pathname"))
print("banner(应无):", ev("!!document.querySelector('.demo-banner')"))

print()
print("=" * 30)
print("8. 滚动修复不受影响（补充信息点击位置保持）")
print("=" * 30)
run(["open", "http://127.0.0.1:8000/index.html?t=p5c"], None, 45)
time.sleep(0.8)
ev("sessionStorage.clear(); 'ok'")
ev("document.querySelector('.choice.entry[data-target=family]').click(); 'ok'")
time.sleep(1.0)
ev("document.querySelector('#operatorGrid .choice[data-role=\"女儿\"]').click(); 'ok'")
ev("document.querySelector('#beneficiaryGrid .choice[data-role=\"父亲\"]').click(); 'ok'")
ev("document.getElementById('nextBtn').click(); 'ok'")
time.sleep(1.2)
ev("document.getElementById('situation').value='我父亲72岁，在广州生活，最近行动不方便'; 'ok'")
ev("document.getElementById('discoverBtn').click(); 'ok'")
time.sleep(3.0)
ev("document.querySelector('[data-confirm=hukou][data-value=true]').scrollIntoView({block:'center'}); 'ok'")
time.sleep(0.3)
before = ev("Math.round(document.querySelector('[data-confirm=hukou][data-value=true]').getBoundingClientRect().top)")
ev("document.querySelector('[data-confirm=hukou][data-value=true]').click(); 'ok'")
time.sleep(2.2)
after = ev("(() => { const b=document.querySelector('[data-confirm=hukou][data-value=true]'); return b ? Math.round(b.getBoundingClientRect().top) : 'gone'; })()")
print("滚动位置 保持:", before, "->", after, " 一致:", before == after)
